import { describe, expect, it } from 'vitest';
import { generateReadme } from '../../src/services/generate-readme.js';

describe('generateReadme', () => {
  it('generates README content for the project name', () => {
    expect(generateReadme('MyProject')).toBe(`# MyProject

Generated by Atlas CLI.

Repository initialized successfully.

Version

v0.1.0-alpha

Generated With

Atlas CLI
`);
  });
});
