import { access, mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { EMPTY_VALIDATION_RESULT } from '../../src/diagnostics/validation-result.js';
import { createInitProjectService } from '../../src/services/create-init-project-service.js';
import type { FileService } from '../../src/services/file/file-service.js';
import { FilesystemWriter } from '../../src/services/file/filesystem-writer.js';
import { InitProjectError } from '../../src/services/init-project-error.js';
import { InitProjectService } from '../../src/services/init-project-service.js';
import { PROJECT_DIRECTORY_PATHS, PROJECT_ROOT_FILES } from '../../src/services/init-project.js';
import type { GenerationResult } from '../../src/services/project-generation/generation-result.js';
import type { ProjectGenerationPipeline } from '../../src/services/project-generation/project-generation-pipeline.js';
import { FilesystemTemplateLoader } from '../../src/templates/filesystem/filesystem-template-loader.js';

const tempDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

async function createTempDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'atlas-init-service-'));
  tempDirectories.push(directory);
  return directory;
}

async function writeExternalTemplates(templatesDirectory: string): Promise<void> {
  await mkdir(templatesDirectory, { recursive: true });
  await writeFile(
    join(templatesDirectory, 'README.md'),
    '# {{projectName}}\n\nExternal README template.',
  );
  await writeFile(join(templatesDirectory, 'CHANGELOG.md'), '# External Changelog\n');
  await writeFile(join(templatesDirectory, 'PROJECT-DASHBOARD.md'), '# External Dashboard\n');
  await writeFile(join(templatesDirectory, 'governance-index.md'), '# External Governance\n');
}

describe('InitProjectService', () => {
  it('creates a project using the generation pipeline and file service', async () => {
    const baseDirectory = await createTempDirectory();
    const service = createInitProjectService(baseDirectory);

    const result = await service.execute('MyProject');

    const projectRoot = join(baseDirectory, 'MyProject');

    for (const relativePath of PROJECT_DIRECTORY_PATHS) {
      const directoryStat = await stat(join(projectRoot, relativePath));
      expect(directoryStat.isDirectory()).toBe(true);
    }

    expect(await readFile(join(projectRoot, 'README.md'), 'utf8')).toBe(`# MyProject

Generated by Atlas CLI.`);
    expect(await readFile(join(projectRoot, 'CHANGELOG.md'), 'utf8')).toBe(`# Changelog

Initial release.`);
    expect(await readFile(join(projectRoot, 'PROJECT-DASHBOARD.md'), 'utf8')).toBe(
      `# Project Dashboard

Generated by Atlas CLI.`,
    );
    expect(await readFile(join(projectRoot, 'docs/00-governance/README.md'), 'utf8')).toBe(
      `# Governance

Atlas Governance Documents.`,
    );
    expect(await readFile(join(projectRoot, '.gitignore'), 'utf8')).toBe('');
    expect(result.filesCreated.sort()).toEqual([...PROJECT_ROOT_FILES].sort());
    expect(result.directories).toEqual([...PROJECT_DIRECTORY_PATHS]);
  });

  it('invokes the generation pipeline and file service', async () => {
    const baseDirectory = await createTempDirectory();
    const service = createInitProjectService(baseDirectory);
    const pipeline = Reflect.get(service, 'pipeline') as ProjectGenerationPipeline;
    const fileService = Reflect.get(service, 'fileService') as FileService;

    const generateSpy = vi.spyOn(pipeline, 'generate');
    const writeSpy = vi.spyOn(fileService, 'write');

    await service.execute('MyProject');

    expect(generateSpy).toHaveBeenCalledOnce();
    expect(generateSpy).toHaveBeenCalledWith('MyProject');
    expect(writeSpy).toHaveBeenCalledOnce();
  });

  it('reports skipped files from WriteResult', async () => {
    const baseDirectory = await createTempDirectory();
    const writer = new FilesystemWriter();
    const pipeline = {
      generate: vi.fn(
        (): GenerationResult => ({
          projectName: 'MyProject',
          plan: {
            projectName: 'MyProject',
            directories: [...PROJECT_DIRECTORY_PATHS],
            plannedFiles: [],
          },
          generatedFiles: [],
          directories: [...PROJECT_DIRECTORY_PATHS],
          warnings: [],
          errors: [],
          validation: EMPTY_VALIDATION_RESULT,
        }),
      ),
    } as unknown as ProjectGenerationPipeline;
    const fileService = {
      write: vi.fn().mockResolvedValue({
        createdFiles: ['.gitignore', 'PROJECT-DASHBOARD.md'],
        skippedFiles: ['README.md'],
        createdDirectories: [...PROJECT_DIRECTORY_PATHS],
        errors: [],
      }),
    } as unknown as FileService;

    const service = new InitProjectService(pipeline, fileService, writer, baseDirectory);
    const result = await service.execute('MyProject');

    expect(fileService.write).toHaveBeenCalledOnce();
    expect(result.filesSkipped).toEqual(['README.md']);
    expect(result.filesCreated).toEqual(['.gitignore', 'PROJECT-DASHBOARD.md']);
  });

  it('fails when the project directory already exists', async () => {
    const baseDirectory = await createTempDirectory();
    const service = createInitProjectService(baseDirectory);

    await service.execute('MyProject');

    await expect(service.execute('MyProject')).rejects.toThrow(InitProjectError);
    await expect(service.execute('MyProject')).rejects.toThrow(
      'Project directory "MyProject" already exists.',
    );
  });

  it('does not create files inside scaffold directories', async () => {
    const baseDirectory = await createTempDirectory();
    const service = createInitProjectService(baseDirectory);

    await service.execute('MyProject');

    const projectRoot = join(baseDirectory, 'MyProject');
    const projectEntries = await readdir(projectRoot, { withFileTypes: true });

    expect(
      projectEntries
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort(),
    ).toEqual(['.atlas', 'docs']);

    await expect(
      access(join(projectRoot, 'docs', '00-governance', '.gitkeep')),
    ).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('uses built-in templates when no external template directory exists', async () => {
    const baseDirectory = await createTempDirectory();
    const service = createInitProjectService(baseDirectory);

    await service.execute('MyProject');

    const readme = await readFile(join(baseDirectory, 'MyProject', 'README.md'), 'utf8');
    expect(readme).toBe(`# MyProject

Generated by Atlas CLI.`);
  });

  it('uses external templates when the configured template directory exists', async () => {
    const baseDirectory = await createTempDirectory();
    await writeExternalTemplates(join(baseDirectory, 'templates'));
    const service = createInitProjectService(baseDirectory);

    await service.execute('MyProject');

    const readme = await readFile(join(baseDirectory, 'MyProject', 'README.md'), 'utf8');
    expect(readme).toBe(`# MyProject

External README template.`);
    expect(await readFile(join(baseDirectory, 'MyProject', 'CHANGELOG.md'), 'utf8')).toBe(
      '# External Changelog\n',
    );
  });

  it('falls back to built-in templates when the configured directory is missing', async () => {
    const baseDirectory = await createTempDirectory();
    await writeFile(
      join(baseDirectory, 'atlas.config.json'),
      JSON.stringify({
        templates: {
          directory: './missing-templates',
        },
      }),
      'utf8',
    );
    const service = createInitProjectService(baseDirectory);

    await service.execute('MyProject');

    const readme = await readFile(join(baseDirectory, 'MyProject', 'README.md'), 'utf8');
    expect(readme).toBe(`# MyProject

Generated by Atlas CLI.`);
  });

  it('falls back to built-in templates when filesystem template loading fails', async () => {
    const baseDirectory = await createTempDirectory();
    await writeExternalTemplates(join(baseDirectory, 'templates'));
    vi.spyOn(FilesystemTemplateLoader.prototype, 'load').mockImplementation(() => {
      throw new Error('Failed to load templates');
    });
    const service = createInitProjectService(baseDirectory);

    await service.execute('MyProject');

    const readme = await readFile(join(baseDirectory, 'MyProject', 'README.md'), 'utf8');
    expect(readme).toBe(`# MyProject

Generated by Atlas CLI.`);
  });
});
