import { describe, expect, it } from 'vitest';
import { ProjectTemplateContext } from '../../src/templates/context/project-template-context.js';
import { MissingTemplateVariableError } from '../../src/templates/interpolation/template-interpolator-error.js';
import { TemplateInterpolator } from '../../src/templates/interpolation/template-interpolator.js';

describe('TemplateInterpolator', () => {
  it('replaces projectName placeholders', () => {
    const interpolator = new TemplateInterpolator();
    const context = new ProjectTemplateContext('MyProject');

    const result = interpolator.interpolate(
      '# {{projectName}}\n\nGenerated by Atlas CLI.',
      context,
    );

    expect(result).toBe('# MyProject\n\nGenerated by Atlas CLI.');
  });

  it('replaces multiple placeholders', () => {
    const interpolator = new TemplateInterpolator();
    const context = new ProjectTemplateContext('MyProject');

    const result = interpolator.interpolate('{{projectName}} / {{projectName}}', context);

    expect(result).toBe('MyProject / MyProject');
  });

  it('throws MissingTemplateVariableError for unknown variables', () => {
    const interpolator = new TemplateInterpolator();
    const context = new ProjectTemplateContext('MyProject');

    expect(() => interpolator.interpolate('{{unknown}}', context)).toThrow(
      MissingTemplateVariableError,
    );
    expect(() => interpolator.interpolate('{{unknown}}', context)).toThrow(
      'Template variable "unknown" could not be resolved.',
    );
  });
});
