import { describe, expect, it } from 'vitest';
import { CHANGELOG_TEMPLATE_ID } from '../../src/templates/catalog/changelog-template.js';
import { GOVERNANCE_INDEX_TEMPLATE_ID } from '../../src/templates/catalog/governance-index-template.js';
import { PROJECT_DASHBOARD_TEMPLATE_ID } from '../../src/templates/catalog/project-dashboard-template.js';
import { README_TEMPLATE_ID } from '../../src/templates/catalog/readme-template.js';
import { TemplateCatalog } from '../../src/templates/catalog/template-catalog.js';
import { InMemoryTemplateRegistry } from '../../src/templates/registry/in-memory-template-registry.js';

const EXPECTED_TEMPLATE_IDS = [
  README_TEMPLATE_ID,
  CHANGELOG_TEMPLATE_ID,
  PROJECT_DASHBOARD_TEMPLATE_ID,
  GOVERNANCE_INDEX_TEMPLATE_ID,
] as const;

describe('TemplateCatalog', () => {
  it('registerDefaults registers all governance templates', () => {
    const registry = new InMemoryTemplateRegistry();
    const catalog = new TemplateCatalog();

    catalog.registerDefaults(registry);

    expect(registry.list()).toHaveLength(EXPECTED_TEMPLATE_IDS.length);

    for (const templateId of EXPECTED_TEMPLATE_IDS) {
      expect(registry.has(templateId)).toBe(true);
    }
  });

  it('keeps README template content unchanged', () => {
    const registry = new InMemoryTemplateRegistry();
    const catalog = new TemplateCatalog();

    catalog.registerDefaults(registry);

    const readme = registry.get(README_TEMPLATE_ID);

    expect(readme?.template).toMatchObject({
      content: `# {{projectName}}

Generated by Atlas CLI.`,
    });
  });
});
