import { describe, expect, it } from 'vitest';
import {
  README_TEMPLATE_ID,
  type ReadmeTemplate,
} from '../../src/templates/catalog/readme-template.js';
import { TemplateCatalog } from '../../src/templates/catalog/template-catalog.js';
import { InMemoryTemplateRegistry } from '../../src/templates/registry/in-memory-template-registry.js';
import { isStringTemplate } from '../../src/templates/types/string-template.js';

describe('TemplateCatalog', () => {
  it('registerDefaults registers README exactly once', () => {
    const registry = new InMemoryTemplateRegistry();
    const catalog = new TemplateCatalog();

    catalog.registerDefaults(registry);

    expect(registry.list()).toHaveLength(1);

    const registration = registry.get(README_TEMPLATE_ID);

    expect(registration).toBeDefined();
    expect(registration?.id).toBe(README_TEMPLATE_ID);
    expect(registration?.metadata.category).toBe('documentation');
    expect(isStringTemplate(registration?.template as ReadmeTemplate)).toBe(true);
    expect((registration?.template as ReadmeTemplate).content).toBe(`# {{projectName}}

Generated by Atlas CLI.`);
  });
});
