import type { StringTemplate } from '../types/string-template.js';

export const PROJECT_DASHBOARD_TEMPLATE_ID = 'project-dashboard';

export class ProjectDashboardTemplate implements StringTemplate {
  readonly metadata = {
    id: PROJECT_DASHBOARD_TEMPLATE_ID,
    name: 'Project Dashboard',
  };

  readonly content = `# Project Dashboard

Generated by Atlas CLI.`;
}
