import type { StringTemplate } from '../types/string-template.js';

export const README_TEMPLATE_ID = 'readme';

export class ReadmeTemplate implements StringTemplate {
  readonly metadata = {
    id: README_TEMPLATE_ID,
    name: 'README',
  };

  readonly content = `# {{projectName}}

Generated by Atlas CLI.`;
}
