import { version } from '../version.js';

export function generateReadme(projectName: string): string {
  const formattedVersion = version.startsWith('v') ? version : `v${version}`;

  return `# ${projectName}

Generated by Atlas CLI.

Repository initialized successfully.

Version

${formattedVersion}

Generated With

Atlas CLI
`;
}
