import { access, mkdtemp, readFile, readdir, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Command } from 'commander';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { registerInitCommand } from '../../src/commands/init/index.js';
import { createInitProjectService } from '../../src/services/create-init-project-service.js';
import { PROJECT_DIRECTORY_PATHS, PROJECT_ROOT_FILES } from '../../src/services/init-project.js';
import type { ProjectGenerationPipeline } from '../../src/services/project-generation/project-generation-pipeline.js';

const PROJECT_NAME = 'DemoProject';
const tempDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

async function createTempDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'atlas-e2e-'));
  tempDirectories.push(directory);
  return directory;
}

function createCliProgram(baseDirectory: string): Command {
  const program = new Command();
  registerInitCommand(program, () => createInitProjectService(baseDirectory));
  return program;
}

function expectedReadme(projectName: string): string {
  return `# ${projectName}

Generated by Atlas CLI.`;
}

describe('atlas init E2E', () => {
  it('creates a complete project through CLI, pipeline, validation, and file service', async () => {
    const baseDirectory = await createTempDirectory();
    const program = createCliProgram(baseDirectory);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => undefined);

    await program.parseAsync(['init', PROJECT_NAME], { from: 'user' });

    expect(process.exitCode).not.toBe(1);
    expect(logSpy).toHaveBeenCalledWith(`Successfully initialized Atlas project: ${PROJECT_NAME}`);

    const projectRoot = join(baseDirectory, PROJECT_NAME);

    for (const relativePath of PROJECT_DIRECTORY_PATHS) {
      const directoryPath = join(projectRoot, relativePath);
      const directoryStat = await stat(directoryPath);
      expect(directoryStat.isDirectory(), `expected directory ${relativePath}`).toBe(true);
    }

    const rootEntries = await readdir(projectRoot, { withFileTypes: true });
    const rootDirectories = rootEntries
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
    expect(rootDirectories).toEqual(['.atlas', 'docs']);

    expect(await readFile(join(projectRoot, 'README.md'), 'utf8')).toBe(
      expectedReadme(PROJECT_NAME),
    );
    expect(await readFile(join(projectRoot, 'CHANGELOG.md'), 'utf8')).toBe(`# Changelog

Initial release.`);
    expect(await readFile(join(projectRoot, 'PROJECT-DASHBOARD.md'), 'utf8')).toBe(
      `# Project Dashboard

Generated by Atlas CLI.`,
    );
    expect(await readFile(join(projectRoot, 'docs/00-governance/README.md'), 'utf8')).toBe(
      `# Governance

Atlas Governance Documents.`,
    );
    expect(await readFile(join(projectRoot, '.gitignore'), 'utf8')).toBe('');

    const createdFiles = (
      await Promise.all(
        PROJECT_ROOT_FILES.map(async (relativePath) => {
          await access(join(projectRoot, relativePath));
          return relativePath;
        }),
      )
    ).sort();

    expect(createdFiles).toEqual([...PROJECT_ROOT_FILES].sort());

    logSpy.mockRestore();
  });

  it('runs generation validation without errors before writing files', async () => {
    const baseDirectory = await createTempDirectory();
    const service = createInitProjectService(baseDirectory);
    const pipeline = Reflect.get(service, 'pipeline') as ProjectGenerationPipeline;
    const generateSpy = vi.spyOn(pipeline, 'generate');

    await service.execute(PROJECT_NAME);

    expect(generateSpy).toHaveBeenCalledOnce();
    expect(generateSpy).toHaveBeenCalledWith(PROJECT_NAME);

    const generationResult = generateSpy.mock.results[0]?.value;
    expect(generationResult.validation.hasErrors).toBe(false);
    expect(generationResult.validation.hasWarnings).toBe(false);
    expect(generationResult.validation.diagnostics).toEqual([]);
  });

  it('rejects duplicate project initialization', async () => {
    const baseDirectory = await createTempDirectory();
    const program = createCliProgram(baseDirectory);
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    await program.parseAsync(['init', PROJECT_NAME], { from: 'user' });
    await program.parseAsync(['init', PROJECT_NAME], { from: 'user' });

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining(`Project directory "${PROJECT_NAME}" already exists.`),
    );

    errorSpy.mockRestore();
  });
});
