import { access, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { GenerationInspector } from '../../../src/intelligence/inspectors/generation-inspector.js';
import { generationDefaultProfile } from '../../../src/intelligence/profiles/generation-default-profile.js';
import { ValidationEngine } from '../../../src/intelligence/validation/validation-engine.js';
import { FileService } from '../../../src/services/file/file-service.js';
import { FilesystemWriter } from '../../../src/services/file/filesystem-writer.js';
import { PROJECT_DIRECTORY_PATHS, PROJECT_ROOT_FILES } from '../../../src/services/init-project.js';
import { ProjectGenerationPipeline } from '../../../src/services/project-generation/project-generation-pipeline.js';
import { ProjectScaffoldService } from '../../../src/services/project-scaffold-service.js';
import { TemplateCatalog } from '../../../src/templates/catalog/template-catalog.js';
import { DefaultTemplateEngine } from '../../../src/templates/engine/default-template-engine.js';
import { StringTemplateRenderer } from '../../../src/templates/engine/string-template-renderer.js';
import { TemplateInterpolator } from '../../../src/templates/interpolation/template-interpolator.js';
import { InMemoryTemplateRegistry } from '../../../src/templates/registry/in-memory-template-registry.js';

const tempDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

async function createTempDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'atlas-file-service-'));
  tempDirectories.push(directory);
  return directory;
}

function createPipeline(): ProjectGenerationPipeline {
  const registry = new InMemoryTemplateRegistry();
  const catalog = new TemplateCatalog();
  const interpolator = new TemplateInterpolator();
  const renderer = new StringTemplateRenderer(interpolator);
  const engine = new DefaultTemplateEngine(registry, renderer);
  const scaffoldService = new ProjectScaffoldService(catalog, registry, engine);
  const generationInspector = new GenerationInspector();
  const validationEngine = new ValidationEngine(generationDefaultProfile.rules);

  return new ProjectGenerationPipeline(scaffoldService, generationInspector, validationEngine);
}

function createFileService(): FileService {
  return new FileService(new FilesystemWriter());
}

describe('FileService', () => {
  it('creates scaffold directories', async () => {
    const baseDirectory = await createTempDirectory();
    const generationResult = createPipeline().generate('MyProject');
    const fileService = createFileService();

    const writeResult = await fileService.write(baseDirectory, generationResult);

    expect(writeResult.createdDirectories).toEqual([...PROJECT_DIRECTORY_PATHS]);
    expect(writeResult.errors).toEqual([]);

    for (const relativeDirectory of PROJECT_DIRECTORY_PATHS) {
      const directoryPath = join(baseDirectory, 'MyProject', relativeDirectory);
      const directoryStat = await stat(directoryPath);
      expect(directoryStat.isDirectory()).toBe(true);
    }
  });

  it('writes README with rendered content', async () => {
    const baseDirectory = await createTempDirectory();
    const generationResult = createPipeline().generate('MyProject');
    const fileService = createFileService();

    const writeResult = await fileService.write(baseDirectory, generationResult);

    expect(writeResult.createdFiles).toContain('README.md');

    const readmeContent = await readFile(join(baseDirectory, 'MyProject', 'README.md'), 'utf8');
    expect(readmeContent).toBe(`# MyProject

Generated by Atlas CLI.`);
  });

  it('writes generated governance files and empty root files', async () => {
    const baseDirectory = await createTempDirectory();
    const generationResult = createPipeline().generate('MyProject');
    const fileService = createFileService();

    const writeResult = await fileService.write(baseDirectory, generationResult);

    expect(writeResult.createdFiles.sort()).toEqual([...PROJECT_ROOT_FILES].sort());

    expect(await readFile(join(baseDirectory, 'MyProject', 'CHANGELOG.md'), 'utf8')).toBe(
      `# Changelog

Initial release.`,
    );
    expect(await readFile(join(baseDirectory, 'MyProject', '.gitignore'), 'utf8')).toBe('');
  });

  it('skips existing files when overwrite is false', async () => {
    const baseDirectory = await createTempDirectory();
    const generationResult = createPipeline().generate('MyProject');
    const fileService = createFileService();

    await fileService.write(baseDirectory, generationResult);

    const readmePath = join(baseDirectory, 'MyProject', 'README.md');
    await writeFile(readmePath, 'existing content', 'utf8');

    const secondWrite = await fileService.write(baseDirectory, generationResult, {
      overwrite: false,
      encoding: 'utf-8',
      createDirectories: true,
    });

    expect(secondWrite.skippedFiles).toContain('README.md');
    expect(await readFile(readmePath, 'utf8')).toBe('existing content');
  });

  it('preserves UTF-8 content', async () => {
    const baseDirectory = await createTempDirectory();
    const generationResult = createPipeline().generate('MyProject');
    const unicodeResult = {
      ...generationResult,
      generatedFiles: generationResult.generatedFiles.map((file) =>
        file.relativePath === 'README.md'
          ? { ...file, content: '# Café — 日本語\n\nAtlas CLI.' }
          : file,
      ),
    };
    const fileService = createFileService();

    await fileService.write(baseDirectory, unicodeResult);

    const content = await readFile(join(baseDirectory, 'MyProject', 'README.md'), 'utf8');
    expect(content).toBe('# Café — 日本語\n\nAtlas CLI.');
  });

  it('does not modify the GenerationResult', async () => {
    const baseDirectory = await createTempDirectory();
    const generationResult = createPipeline().generate('MyProject');
    const snapshot = structuredClone(generationResult);
    const fileService = createFileService();

    await fileService.write(baseDirectory, generationResult);

    expect(generationResult).toEqual(snapshot);
  });
});
