import { readFileSync } from 'node:fs';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { GenerationInspector } from '../../../src/intelligence/inspectors/generation-inspector.js';
import { generationDefaultProfile } from '../../../src/intelligence/profiles/generation-default-profile.js';
import { ValidationEngine } from '../../../src/intelligence/validation/validation-engine.js';
import { FileService } from '../../../src/services/file/file-service.js';
import { FilesystemWriter } from '../../../src/services/file/filesystem-writer.js';
import { PROJECT_DIRECTORY_PATHS } from '../../../src/services/init-project.js';
import {
  PROJECT_GENERATED_FILE_PATHS,
  TEMPLATED_PROJECT_FILES,
} from '../../../src/services/project-generation/project-generated-files.js';
import { ProjectGenerationPipeline } from '../../../src/services/project-generation/project-generation-pipeline.js';
import { ProjectScaffoldService } from '../../../src/services/project-scaffold-service.js';
import { TemplateCatalog } from '../../../src/templates/catalog/template-catalog.js';
import { DefaultTemplateEngine } from '../../../src/templates/engine/default-template-engine.js';
import { StringTemplateRenderer } from '../../../src/templates/engine/string-template-renderer.js';
import { TemplateInterpolator } from '../../../src/templates/interpolation/template-interpolator.js';
import { InMemoryTemplateRegistry } from '../../../src/templates/registry/in-memory-template-registry.js';

const tempDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

async function createTempDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'atlas-generation-'));
  tempDirectories.push(directory);
  return directory;
}

function createPipelineComponents() {
  const registry = new InMemoryTemplateRegistry();
  const catalog = new TemplateCatalog();
  const interpolator = new TemplateInterpolator();
  const renderer = new StringTemplateRenderer(interpolator);
  const engine = new DefaultTemplateEngine(registry, renderer);
  const scaffoldService = new ProjectScaffoldService(catalog, registry, engine);
  const generationInspector = new GenerationInspector();
  const validationEngine = new ValidationEngine(generationDefaultProfile.rules);

  return { scaffoldService, generationInspector, validationEngine };
}

function createPipeline(
  generationInspector?: GenerationInspector,
  validationEngine?: ValidationEngine,
): ProjectGenerationPipeline {
  const components = createPipelineComponents();

  return new ProjectGenerationPipeline(
    components.scaffoldService,
    generationInspector ?? components.generationInspector,
    validationEngine ?? components.validationEngine,
  );
}

describe('ProjectGenerationPipeline', () => {
  it('includes README in the generation result with rendered content', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');
    const readme = result.generatedFiles.find((file) => file.relativePath === 'README.md');

    expect(readme).toBeDefined();
    expect(readme?.content).toBe(`# MyProject

Generated by Atlas CLI.`);
    expect(readme?.encoding).toBe('utf-8');
  });

  it('includes governance documents in the generation plan', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.plan.plannedFiles.map((file) => file.relativePath).sort()).toEqual(
      [...PROJECT_GENERATED_FILE_PATHS].sort(),
    );
    expect(
      result.plan.plannedFiles.find((file) => file.relativePath === 'CHANGELOG.md')?.templateId,
    ).toBe('changelog');
    expect(
      result.plan.plannedFiles.find((file) => file.relativePath === 'PROJECT-DASHBOARD.md')
        ?.templateId,
    ).toBe('project-dashboard');
    expect(
      result.plan.plannedFiles.find((file) => file.relativePath === 'docs/00-governance/README.md')
        ?.templateId,
    ).toBe('governance-index');
  });

  it('renders governance documents in the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(
      result.generatedFiles.find((file) => file.relativePath === 'CHANGELOG.md')?.content,
    ).toBe(
      `# Changelog

Initial release.`,
    );
    expect(
      result.generatedFiles.find((file) => file.relativePath === 'PROJECT-DASHBOARD.md')?.content,
    ).toBe(`# Project Dashboard

Generated by Atlas CLI.`);
    expect(
      result.generatedFiles.find((file) => file.relativePath === 'docs/00-governance/README.md')
        ?.content,
    ).toBe(`# Governance

Atlas Governance Documents.`);
    expect(result.generatedFiles.find((file) => file.relativePath === '.gitignore')?.content).toBe(
      '',
    );
  });

  it('lists scaffold directories in the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.directories).toEqual([...PROJECT_DIRECTORY_PATHS]);
    expect(result.plan.directories).toEqual([...PROJECT_DIRECTORY_PATHS]);
    expect(result.plan.projectName).toBe('MyProject');
  });

  it('writes all generated files through FileService', async () => {
    const baseDirectory = await createTempDirectory();
    const pipeline = createPipeline();
    const generationResult = pipeline.generate('MyProject');
    const fileService = new FileService(new FilesystemWriter());

    const writeResult = await fileService.write(baseDirectory, generationResult);

    expect(writeResult.createdFiles.sort()).toEqual([...PROJECT_GENERATED_FILE_PATHS].sort());

    for (const file of TEMPLATED_PROJECT_FILES) {
      const content = await readFile(join(baseDirectory, 'MyProject', file.relativePath), 'utf8');
      expect(content.length).toBeGreaterThan(0);
    }
  });

  it('attaches validation result to the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.validation).toBeDefined();
    expect(result.validation.diagnostics).toEqual([]);
    expect(result.validation.hasErrors).toBe(false);
    expect(result.validation.hasWarnings).toBe(false);
    expect(Object.keys(result.validation).sort()).toEqual(
      ['diagnostics', 'hasErrors', 'hasWarnings'].sort(),
    );
  });

  it('executes ValidationEngine through GenerationInspector during generation', () => {
    const { scaffoldService, generationInspector, validationEngine } = createPipelineComponents();
    const inspectSpy = vi.spyOn(generationInspector, 'inspect');
    const validateSpy = vi.spyOn(validationEngine, 'validate');
    const pipeline = new ProjectGenerationPipeline(
      scaffoldService,
      generationInspector,
      validationEngine,
    );

    pipeline.generate('MyProject');

    expect(inspectSpy).toHaveBeenCalledOnce();
    expect(validateSpy).toHaveBeenCalledOnce();
  });

  it('executes all five generation-default rules', () => {
    const { scaffoldService, generationInspector, validationEngine } = createPipelineComponents();
    const validateSpy = vi.spyOn(validationEngine, 'validate');
    const pipeline = new ProjectGenerationPipeline(
      scaffoldService,
      generationInspector,
      validationEngine,
    );

    pipeline.generate('MyProject');

    expect(validateSpy.mock.results[0]?.value.rulesExecuted).toBe(5);
  });

  it('fails validation when README.md is missing from the inspection subject', () => {
    const { scaffoldService, validationEngine } = createPipelineComponents();
    const generationInspector = new GenerationInspector();
    vi.spyOn(generationInspector, 'inspect').mockImplementation((input) => {
      const subject = new GenerationInspector().inspect(input);

      return {
        ...subject,
        files: subject.files.filter((file) => file.relativePath !== 'README.md'),
      };
    });
    const pipeline = new ProjectGenerationPipeline(
      scaffoldService,
      generationInspector,
      validationEngine,
    );

    const result = pipeline.generate('MyProject');

    expect(result.validation.hasErrors).toBe(true);
    expect(result.validation.diagnostics).toEqual([
      expect.objectContaining({
        code: 'README_MISSING',
        path: 'README.md',
      }),
    ]);
  });

  it('fails validation when PROJECT-DASHBOARD.md is missing from the inspection subject', () => {
    const { scaffoldService, validationEngine } = createPipelineComponents();
    const generationInspector = new GenerationInspector();
    vi.spyOn(generationInspector, 'inspect').mockImplementation((input) => {
      const subject = new GenerationInspector().inspect(input);

      return {
        ...subject,
        files: subject.files.filter((file) => file.relativePath !== 'PROJECT-DASHBOARD.md'),
      };
    });
    const pipeline = new ProjectGenerationPipeline(
      scaffoldService,
      generationInspector,
      validationEngine,
    );

    const result = pipeline.generate('MyProject');

    expect(result.validation.hasErrors).toBe(true);
    expect(result.validation.diagnostics).toEqual([
      expect.objectContaining({
        code: 'PROJECT_DASHBOARD_MISSING',
        path: 'PROJECT-DASHBOARD.md',
      }),
    ]);
  });

  it('contains no filesystem dependency in pipeline source', () => {
    const currentDirectory = dirname(fileURLToPath(import.meta.url));
    const pipelineSource = readFileSync(
      join(
        currentDirectory,
        '../../../src/services/project-generation/project-generation-pipeline.ts',
      ),
      'utf8',
    );

    expect(pipelineSource).not.toMatch(/node:fs/);
    expect(pipelineSource).not.toMatch(/\bmkdir\b/);
    expect(pipelineSource).not.toMatch(/\bwriteFile\b/);
  });
});
