import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { PROJECT_DIRECTORY_PATHS } from '../../../src/services/init-project.js';
import { ProjectGenerationPipeline } from '../../../src/services/project-generation/project-generation-pipeline.js';
import { ProjectScaffoldService } from '../../../src/services/project-scaffold-service.js';
import { TemplateCatalog } from '../../../src/templates/catalog/template-catalog.js';
import { DefaultTemplateEngine } from '../../../src/templates/engine/default-template-engine.js';
import { StringTemplateRenderer } from '../../../src/templates/engine/string-template-renderer.js';
import { TemplateInterpolator } from '../../../src/templates/interpolation/template-interpolator.js';
import { InMemoryTemplateRegistry } from '../../../src/templates/registry/in-memory-template-registry.js';

function createPipeline(): ProjectGenerationPipeline {
  const registry = new InMemoryTemplateRegistry();
  const catalog = new TemplateCatalog();
  const interpolator = new TemplateInterpolator();
  const renderer = new StringTemplateRenderer(interpolator);
  const engine = new DefaultTemplateEngine(registry, renderer);
  const scaffoldService = new ProjectScaffoldService(catalog, registry, engine);

  return new ProjectGenerationPipeline(scaffoldService);
}

describe('ProjectGenerationPipeline', () => {
  it('includes README in the generation result with rendered content', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');
    const readme = result.generatedFiles.find((file) => file.relativePath === 'README.md');

    expect(readme).toBeDefined();
    expect(readme?.content).toBe(`# MyProject

Generated by Atlas CLI.`);
    expect(readme?.encoding).toBe('utf-8');
  });

  it('lists scaffold directories in the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.directories).toEqual([...PROJECT_DIRECTORY_PATHS]);
    expect(result.plan.directories).toEqual([...PROJECT_DIRECTORY_PATHS]);
    expect(result.plan.projectName).toBe('MyProject');
  });

  it('includes empty root files in the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.generatedFiles.map((file) => file.relativePath).sort()).toEqual([
      '.gitignore',
      'CHANGELOG.md',
      'README.md',
    ]);
    expect(
      result.generatedFiles.find((file) => file.relativePath === 'CHANGELOG.md')?.content,
    ).toBe('');
    expect(result.generatedFiles.find((file) => file.relativePath === '.gitignore')?.content).toBe(
      '',
    );
  });

  it('contains no filesystem dependency in pipeline source', () => {
    const currentDirectory = dirname(fileURLToPath(import.meta.url));
    const pipelineSource = readFileSync(
      join(
        currentDirectory,
        '../../../src/services/project-generation/project-generation-pipeline.ts',
      ),
      'utf8',
    );
    const generatedFileSource = readFileSync(
      join(currentDirectory, '../../../src/services/project-generation/generated-file.ts'),
      'utf8',
    );
    const generationPlanSource = readFileSync(
      join(currentDirectory, '../../../src/services/project-generation/generation-plan.ts'),
      'utf8',
    );
    const generationResultSource = readFileSync(
      join(currentDirectory, '../../../src/services/project-generation/generation-result.ts'),
      'utf8',
    );

    for (const source of [
      pipelineSource,
      generatedFileSource,
      generationPlanSource,
      generationResultSource,
    ]) {
      expect(source).not.toMatch(/node:fs/);
      expect(source).not.toMatch(/\bmkdir\b/);
      expect(source).not.toMatch(/\bwriteFile\b/);
    }
  });
});
