import { readFileSync } from 'node:fs';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { afterEach } from 'vitest';
import { createDefaultProjectValidator } from '../../../src/diagnostics/create-default-project-validator.js';
import { FileService } from '../../../src/services/file/file-service.js';
import { FilesystemWriter } from '../../../src/services/file/filesystem-writer.js';
import { PROJECT_DIRECTORY_PATHS } from '../../../src/services/init-project.js';
import {
  PROJECT_GENERATED_FILE_PATHS,
  TEMPLATED_PROJECT_FILES,
} from '../../../src/services/project-generation/project-generated-files.js';
import { ProjectGenerationPipeline } from '../../../src/services/project-generation/project-generation-pipeline.js';
import { ProjectScaffoldService } from '../../../src/services/project-scaffold-service.js';
import { TemplateCatalog } from '../../../src/templates/catalog/template-catalog.js';
import { DefaultTemplateEngine } from '../../../src/templates/engine/default-template-engine.js';
import { StringTemplateRenderer } from '../../../src/templates/engine/string-template-renderer.js';
import { TemplateInterpolator } from '../../../src/templates/interpolation/template-interpolator.js';
import { InMemoryTemplateRegistry } from '../../../src/templates/registry/in-memory-template-registry.js';

const tempDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

async function createTempDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'atlas-generation-'));
  tempDirectories.push(directory);
  return directory;
}

function createPipeline(): ProjectGenerationPipeline {
  const registry = new InMemoryTemplateRegistry();
  const catalog = new TemplateCatalog();
  const interpolator = new TemplateInterpolator();
  const renderer = new StringTemplateRenderer(interpolator);
  const engine = new DefaultTemplateEngine(registry, renderer);
  const scaffoldService = new ProjectScaffoldService(catalog, registry, engine);

  return new ProjectGenerationPipeline(scaffoldService, createDefaultProjectValidator());
}

describe('ProjectGenerationPipeline', () => {
  it('includes README in the generation result with rendered content', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');
    const readme = result.generatedFiles.find((file) => file.relativePath === 'README.md');

    expect(readme).toBeDefined();
    expect(readme?.content).toBe(`# MyProject

Generated by Atlas CLI.`);
    expect(readme?.encoding).toBe('utf-8');
  });

  it('includes governance documents in the generation plan', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.plan.plannedFiles.map((file) => file.relativePath).sort()).toEqual(
      [...PROJECT_GENERATED_FILE_PATHS].sort(),
    );
    expect(
      result.plan.plannedFiles.find((file) => file.relativePath === 'CHANGELOG.md')?.templateId,
    ).toBe('changelog');
    expect(
      result.plan.plannedFiles.find((file) => file.relativePath === 'PROJECT-DASHBOARD.md')
        ?.templateId,
    ).toBe('project-dashboard');
    expect(
      result.plan.plannedFiles.find((file) => file.relativePath === 'docs/00-governance/README.md')
        ?.templateId,
    ).toBe('governance-index');
  });

  it('renders governance documents in the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(
      result.generatedFiles.find((file) => file.relativePath === 'CHANGELOG.md')?.content,
    ).toBe(
      `# Changelog

Initial release.`,
    );
    expect(
      result.generatedFiles.find((file) => file.relativePath === 'PROJECT-DASHBOARD.md')?.content,
    ).toBe(`# Project Dashboard

Generated by Atlas CLI.`);
    expect(
      result.generatedFiles.find((file) => file.relativePath === 'docs/00-governance/README.md')
        ?.content,
    ).toBe(`# Governance

Atlas Governance Documents.`);
    expect(result.generatedFiles.find((file) => file.relativePath === '.gitignore')?.content).toBe(
      '',
    );
  });

  it('lists scaffold directories in the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.directories).toEqual([...PROJECT_DIRECTORY_PATHS]);
    expect(result.plan.directories).toEqual([...PROJECT_DIRECTORY_PATHS]);
    expect(result.plan.projectName).toBe('MyProject');
  });

  it('writes all generated files through FileService', async () => {
    const baseDirectory = await createTempDirectory();
    const pipeline = createPipeline();
    const generationResult = pipeline.generate('MyProject');
    const fileService = new FileService(new FilesystemWriter());

    const writeResult = await fileService.write(baseDirectory, generationResult);

    expect(writeResult.createdFiles.sort()).toEqual([...PROJECT_GENERATED_FILE_PATHS].sort());

    for (const file of TEMPLATED_PROJECT_FILES) {
      const content = await readFile(join(baseDirectory, 'MyProject', file.relativePath), 'utf8');
      expect(content.length).toBeGreaterThan(0);
    }
  });

  it('attaches validation result to the generation result', () => {
    const pipeline = createPipeline();

    const result = pipeline.generate('MyProject');

    expect(result.validation).toBeDefined();
    expect(result.validation.diagnostics).toEqual([]);
    expect(result.validation.hasErrors).toBe(false);
    expect(result.validation.hasWarnings).toBe(false);
  });

  it('contains no filesystem dependency in pipeline source', () => {
    const currentDirectory = dirname(fileURLToPath(import.meta.url));
    const pipelineSource = readFileSync(
      join(
        currentDirectory,
        '../../../src/services/project-generation/project-generation-pipeline.ts',
      ),
      'utf8',
    );

    expect(pipelineSource).not.toMatch(/node:fs/);
    expect(pipelineSource).not.toMatch(/\bmkdir\b/);
    expect(pipelineSource).not.toMatch(/\bwriteFile\b/);
  });
});
