import { describe, expect, it } from 'vitest';
import type { InspectionFile } from '../../src/intelligence/models/inspection-file.js';
import { InspectionOrigin } from '../../src/intelligence/models/inspection-origin.js';
import type { InspectionSubject } from '../../src/intelligence/models/inspection-subject.js';

const SAMPLE_FILE: InspectionFile = {
  relativePath: 'README.md',
  content: '# DemoProject\n\nGenerated by Atlas CLI.',
  encoding: 'utf-8',
  size: 40,
  checksum: 'abc123',
  metadata: {
    source: 'generation',
  },
};

const SAMPLE_SUBJECT: InspectionSubject = {
  id: 'subject-001',
  origin: InspectionOrigin.Generation,
  projectName: 'DemoProject',
  generatedAt: '2026-07-12T12:00:00.000Z',
  files: [SAMPLE_FILE],
  metadata: {
    inspectorId: 'generation',
    inspectorVersion: '0.0.0',
  },
};

describe('InspectionOrigin', () => {
  it('defines the canonical origin values', () => {
    expect(InspectionOrigin.Generation).toBe('generation');
    expect(InspectionOrigin.Filesystem).toBe('filesystem');
    expect(InspectionOrigin.Remote).toBe('remote');
    expect(InspectionOrigin.Plugin).toBe('plugin');
    expect(Object.values(InspectionOrigin)).toEqual([
      'generation',
      'filesystem',
      'remote',
      'plugin',
    ]);
  });
});

describe('InspectionSubject', () => {
  it('constructs with required fields', () => {
    expect(SAMPLE_SUBJECT.id).toBe('subject-001');
    expect(SAMPLE_SUBJECT.origin).toBe('generation');
    expect(SAMPLE_SUBJECT.projectName).toBe('DemoProject');
    expect(SAMPLE_SUBJECT.generatedAt).toBe('2026-07-12T12:00:00.000Z');
  });

  it('preserves the readonly file collection', () => {
    const files: readonly InspectionFile[] = [
      SAMPLE_FILE,
      {
        relativePath: 'CHANGELOG.md',
        content: '# Changelog\n\nInitial release.',
        encoding: 'utf-8',
        size: 28,
      },
    ];

    const subject: InspectionSubject = {
      ...SAMPLE_SUBJECT,
      files,
    };

    expect(subject.files).toHaveLength(2);
    expect(subject.files[0]?.relativePath).toBe('README.md');
    expect(subject.files[1]?.relativePath).toBe('CHANGELOG.md');
    expect([...subject.files]).toEqual([...files]);
  });

  it('preserves metadata on the subject and files', () => {
    expect(SAMPLE_SUBJECT.metadata).toEqual({
      inspectorId: 'generation',
      inspectorVersion: '0.0.0',
    });
    expect(SAMPLE_SUBJECT.files[0]?.metadata).toEqual({
      source: 'generation',
    });
  });

  it('supports optional file fields without requiring checksum or metadata', () => {
    const file: InspectionFile = {
      relativePath: '.gitignore',
      content: '',
      encoding: 'utf-8',
      size: 0,
    };

    const subject: InspectionSubject = {
      ...SAMPLE_SUBJECT,
      files: [file],
    };

    expect(subject.files[0]?.checksum).toBeUndefined();
    expect(subject.files[0]?.metadata).toBeUndefined();
  });

  it('exposes readonly structural fields', () => {
    const subject: InspectionSubject = SAMPLE_SUBJECT;

    expect(Object.keys(subject)).toEqual([
      'id',
      'origin',
      'projectName',
      'generatedAt',
      'files',
      'metadata',
    ]);
    expect(Object.isFrozen(subject)).toBe(false);
    expect(Object.isFrozen(subject.files)).toBe(false);
    expect(Object.isFrozen(subject.metadata)).toBe(false);
  });
});
